### ISSUE TITLE
Use button instead of anchor

### ISSUE THREAD

**Issue by blurfx** [DevCommunity-ko/Front#6]
https://github.com/DevCommunity-ko/Front/blob/c00d64aa57e41907fff9316c4593b3b8effb59bf/src/components/auth/RegisterField.tsx#L59

`RegisterField` 컴포넌트에서 '나중에 입력할게요'로 사용되는 컴포넌트를 지금 `anchor (a)`로 쓰고있는데요, `a`는 다른 페이지로 이동할 때 사용하는게 주 목적이기에, 클릭 후 임의의 액션을 처리해야 한다면 `button`을 쓰는게 더 옳을 것 같습니다.

**Comment by SolKimDev** [comment]
좋습니다. 현재 아무 동작도 처리되지 않는 상태여서 별 생각 없이 임시로 a를 달아뒀었는데, 버튼을 누르면 API Call이 발생해야 하니 나중을 생각하면 button으로 하는게 더 적합하겠네요.
